import {
  Calendar,
  Gamepad2,
  Gift,
  MonitorSmartphone,
  Boxes,
  Star,
  Hourglass,
  Tag,
  Zap,
  Trophy,
  ShieldCheck,
  Music,
  Film,
  Cloud,
  Cpu,
  Smartphone,
  KeyRound,
  Users,
  Sparkles,
  Layers,
  Flame,
  CreditCard,
  Headphones,
  Menu,
  Gem,
  Globe,
} from 'lucide-react';

export const MENU_ICONS = {
  calendar: Calendar,
  gamepad: Gamepad2,
  gift: Gift,
  monitor: MonitorSmartphone,
  box: Boxes,
  star: Star,
  hourglass: Hourglass,
  tag: Tag,
  zap: Zap,
  trophy: Trophy,
  shield: ShieldCheck,
  music: Music,
  film: Film,
  cloud: Cloud,
  cpu: Cpu,
  phone: Smartphone,
  key: KeyRound,
  users: Users,
  sparkles: Sparkles,
  layers: Layers,
  flame: Flame,
  card: CreditCard,
  headphones: Headphones,
  menu: Menu,
  gem: Gem,
  globe: Globe,
};

export const MENU_ICON_KEYS = Object.keys(MENU_ICONS);

export const getMenuIcon = (key) => MENU_ICONS[key] || Boxes;
