import api from '@lib/axios';

export const adminAPI = {
  getDashboardStats: () => api.get('/admin/dashboard/stats'),
  // Phase 2: platform-wide payout balance (same source as seller balance API).
  getPlatformPayoutBalance: () => api.get('/payout/admin/platform-balance'),
  getOrderPayoutLines: (orderId) => api.get(`/payout/order/${orderId}/lines`),
  getPendingSellers: (params) => api.get('/admin/sellers/pending', { params }),
  getAllSellers: (params) => api.get('/admin/sellers', { params }),
  getSellerDetails: (sellerId) => api.get(`/admin/seller/${sellerId}`),
  approveSeller: (sellerId) => api.post(`/admin/seller/${sellerId}/approve`),
  rejectSeller: (sellerId, data) => api.post(`/admin/seller/${sellerId}/reject`, data),
  blockSeller: (sellerId, data) => api.post(`/admin/seller/${sellerId}/block`, data),
  // CLIENT REQ (seller control): reversible account hold + lift.
  holdSeller: (sellerId, data) => api.post(`/admin/seller/${sellerId}/hold`, data),
  liftSellerHold: (sellerId) => api.post(`/admin/seller/${sellerId}/unhold`),
  getPendingProducts: (params) => api.get('/admin/products/pending', { params }),
  getAllProducts: (params) => api.get('/admin/products', { params }),
  getProductDetails: (productId) => api.get(`/admin/product/${productId}`),
  approveProduct: (productId) => api.post(`/admin/product/${productId}/approve`),
  rejectProduct: (productId, data) => api.post(`/admin/product/${productId}/reject`, data),
  deleteProduct: (productId) => api.delete(`/admin/products/${productId}`),
  getAllPayouts: (params) => api.get('/admin/payouts', { params }),
  getOrderPayoutDetails: (orderId) => api.get(`/payout/admin/order/${orderId}`),
  // Phase 5: admin withdrawal lifecycle management.
  listWithdrawals: (params) => api.get('/withdrawal/admin', { params }),
  getWithdrawal: (id) => api.get(`/withdrawal/${id}`),
  approveWithdrawal: (id) => api.patch(`/withdrawal/${id}/approve`),
  rejectWithdrawal: (id, data) => api.patch(`/withdrawal/${id}/reject`, data),
  retryWithdrawal: (id) => api.post(`/withdrawal/${id}/retry`),
  getAllUsers: (params) => api.get('/admin/users', { params }),
  banUser: (userId, data) => api.post(`/admin/user/${userId}/ban`, data),
  getCommissionRate: () => api.get('/admin/settings/commission-rate'),
  updateCommissionRate: (data) => api.patch('/admin/settings/commission-rate', data),
  getPlusDiscount: () => api.get('/admin/settings/plus-discount'),
  updatePlusDiscount: (data) => api.patch('/admin/settings/plus-discount', data),
  getFeaturedCommission: () => api.get('/admin/settings/featured-commission'),
  updateFeaturedCommission: (data) => api.patch('/admin/settings/featured-commission', data),
  getAutoApproveSetting: () => api.get('/admin/settings/auto-approve-products'),
  updateAutoApproveSetting: (data) => api.patch('/admin/settings/auto-approve-products', data),
  getHomePageSEO: () => api.get('/admin/settings/seo/home'),
  updateHomePageSEO: (data) => api.patch('/admin/settings/seo/home', data),
  getBuyerHandlingFeeSetting: () => api.get('/admin/settings/buyer-handling-fee'),
  updateBuyerHandlingFeeSetting: (data) => api.patch('/admin/settings/buyer-handling-fee', data),
  getBuyerProtectionFeeSetting: () => api.get('/admin/settings/buyer-protection-fee'),
  updateBuyerProtectionFeeSetting: (data) => api.patch('/admin/settings/buyer-protection-fee', data),
  getPayoutSettings: () => api.get('/admin/settings/payouts'),
  updatePayoutSettings: (data) => api.patch('/admin/settings/payouts', data),
  getHandlingFeeStats: () => api.get('/admin/stats/handling-fees'),
  getAllSupportChats: (params) => api.get('/support/admin/chats', { params }),
  assignAdminToChat: (chatId, assignTo = null) => api.post(`/support/admin/${chatId}/assign`, assignTo ? { assignTo } : {}),
  unassignChat: (chatId) => api.post(`/support/admin/${chatId}/unassign`, {}),
  updateChatPriority: (chatId, priority) => api.patch(`/support/admin/${chatId}/priority`, { priority }),
  updateChatStatus: (chatId, status) => api.patch(`/support/admin/${chatId}/status`, { status }),
  getSupportStats: () => api.get('/support/admin/stats'),
  // Canned responses
  getCannedResponses: () => api.get('/support/admin/canned'),
  createCannedResponse: (data) => api.post('/support/admin/canned', data),
  updateCannedResponse: (id, data) => api.patch(`/support/admin/canned/${id}`, data),
  deleteCannedResponse: (id) => api.delete(`/support/admin/canned/${id}`),
  moderateChat: (conversationId, data) => api.post(`/admin/chat/${conversationId}/moderate`, data),
  // Phase 4 (RETIRED): manual verify is gone. Verification is now automatic
  // via PayPal OAuth. The route still returns 410 on the backend.
  blockPayoutAccount: (accountId, data) => api.patch(`/payout-account/${accountId}/block`, data),
  getSellerPayoutAccount: (sellerId) => api.get(`/payout-account/seller/${sellerId}`),
  getSellersPayoutStatus: (params) => api.get('/payout-account/sellers/status', { params }),
  createBundleDeal: (formData) => api.post('/bundle-deal', formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
  }),
  getAllBundleDeals: (params) => api.get('/bundle-deal', { params }),
  getBundleDealById: (id) => api.get(`/bundle-deal/${id}`),
  updateBundleDeal: (id, formData) => api.patch(`/bundle-deal/${id}`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
  }),
  deleteBundleDeal: (id) => api.delete(`/bundle-deal/${id}`),
  toggleBundleDealStatus: (id) => api.patch(`/bundle-deal/${id}/toggle-status`),
  updateProductFeaturedSettings: (productId, data) => api.patch(`/admin/product/${productId}/featured`, data),
};
